PRAGMA foreign_keys = ON;

INSERT INTO tasks(title, description)
VALUES
('Input specific values displayed in the image', 'You will be presented an image of a gym cardio workout console. Your task is to identify and input the duration, distance and calorie values.'),
('Are these receipts the same?', 'Tell us if two receipts are the same'),
('Verify a single value from a receipt', 'Verify the value of single data point (such as store, payment information, date, total etc) as displayed on the receipt'),
('Quick Market Research Survey', 'Participate in market research surveys of your choice. Each survey will receive a reward. Successful survey completions will result in a bonus being reward. Each survey will show the bonus reward value and estimated time to complete.'),
('Is it a real photograph or a person?', 'Look on image for more than 10 seconds and answer the question'),
('QC Reject – Earn up to $0.20 per media minute', 'Rework QC rejected full-text review jobs.'),
('Transcribe email from audio recording', 'Transcribe email from audio recording'),
('Type the text from the images, carefully. Productivity and bonuses guaranteed.', 'Type the text carefully'),
('Demographics survey', 'Demographics survey'),
('Appliance Image Entry', 'Enter the model and serial numbers from the image provided'),
('Extract summary information from 24 shopping receipts (Total)', 'Extract summary information from 24 shopping receipts (Total)'),
('Effects of Anxiety/Procrastination on Performance', 'This study is meant to test the effects of trait anxiety and procrastination on performance of a difficult task. Once you complete a ~40 question survey, you will be asked to make an audio-visual recording of yourself singing a song of your choice.'),
('Annotate Tweet Stance', 'Annotate the stance of tweets towards immigration. This is a long-term work and we will release much more HITs later.'),
('Moderate Customer-Supplied Vacation Rental Reviews (WARNING: This HIT may contain adult content)', 'Moderate 5 reviews/text against a set of guidelines, flagging specific issues.'),
('Quick Study(~ 4 minutes)', 'survey'),
('Identify the brands featured in banner ads – 2021-12-04 22:00:19', 'Type the brand name found in a series of banner ads.'),
('Consumer Prefetences(~ 4 minutes)', 'Share your opinions and answer questions'),
('Find the Legal Entity Identifier for a company', 'Visit a website to find the Legal Entity Identifier for a company (avg. duration under 1 minute, no adult content). *** New task, under development, feedback welcome ***'),
('Help us choose a poster for London Underground', 'We are a brand of nutritional supplements. We would like to know your opinion on our London Underground poster designs.'),
('Join our panel for Ongoing Tasks and Surveys', 'You will be joining a research panel by completing this HIT. You will receive regular surveys and tasks that will be designed to pay $15/hr.'),
('Extract Data From Shopping Receipt', 'If the shopping receipt image is readable extract items and quantities that are not blackened out'),
('Service robot: human likeness, privacy and appropriate scenarios to adopt', 'Give us your opinion about different service robot design and usage intention. We redo this survey with different robot designs.'),
('Answer a survey about images', 'Give us your opinion on a series of questions'),
('Employee job attitudes and behaviors – Part 1(~ 15 minutes)', 'This is a two part study examining employees’ job attitudes and behaviors.'),
('Test a simple mobile app for 5 minutes and answer a 7 minutes survey (~ 12 minutes)', 'Test a free app where you can wear virtual shoes and answer a survey about your experience'),
('Recall the words you’ve seen (< 15 min)', 'HELP US DISCOVER HOW HUMAN MEMORY WORKS! This is a recall experiment. You will see a list of words flashed on the screen one after another. Your task is to recall as many words as you can in an arbitrary order and to report them by typing them in a text box separated by ENTER, SPACE, or COMMA. This is a challenging task so we do not expect that you can recall many words. This is timed task. If you elected to perform it, do it right away, otherwise you would have no time to finish it.'),
('Word Perception Study(~ 60 minutes)', 'Complete a computerized Task on Inquisit'),
('Transcribe data', 'Please transcribe the data from the following images'),
('A two-part study about decision making (2/2)(~ 9 minutes)', 'This is the second part of a two-part study about decision-making. You are invited to participate in the present study because you successfully completed the first part of the study on the same topic on Wednesday. The present study will take approximately 9 minutes to complete, and you will receive $1.00 as the participation fee for successfully completing the study, in addition, you can potentially earn a bonus of up to $3.75. We ask you to pay attention when answering the questions. The study contains attention check questions, and you are required to answer them correctly to receive the participation fee.'),
('Classify fruit', 'Enter the correct name for the fruit'),
('Categorize this business (6 cent bonus for matched answer!)', 'Determine the best category for the business from its name and website (6 cent bonus if your answer matches with another independent worker’s!)'),
('Tell us what this item is – Soft Goods – Batch ID #40578', 'Following the rules in the HIT, select an item name for this HIT.'),
('Answer a survey about a marketing research', 'A survey about online shopping with AR(Augmented Reality) technology. The questionnaire will require approximately 10 minutes to complete.'),
('Students Only!!! Rate Your University Education & Experiences', 'You are invited to participate in a study where you can rate what you feel is important to your university education and/or experience. You will have a chance to reflect on and identify what is valuable to undergraduate students!'),
('Dallinger Compensation HIT', 'For compensation only; no task required.'),
('Answer a survey about your opinions', 'Complete a survey successfully and you will get the reward.'),
('Online patient communities(~ 15 minutes)', 'Please tell us your opinion about online patient communities'),
('Answer Three Queries for these Images!', 'Answer three questions of social media using 5 photos'),
('Nudging people to responsible behavior in gas consumption', 'Master Thesis on importance of features in applications that attempt to improve the choices made by users in the context of gas consumption.'),
('Social Perception Task(~ 30 minutes)', 'You will be asked to complete a 30 minute social perception task and fill out questionnaires about demographics, your political orientation, and your social perceptions. We will pay you $3.00 for your participation.'),
('Survey on chrome extension page(Shahyaan)', 'This survey HIT is about your feelings for a chrome extension page.'),
('Analogies in webpages', 'Identify whether a webpage contains any analogies or not. Highlight any analogies, if present.'),
('Answer a survey about Managing Mental Health', 'Respond to multiple choice questions about how you handle managing mental health challenges and emotional concerns, your attitudes towards seeking mental health services, past mental health service use, and supports you may use.'),
('$1.00 HIT – Easy Followup to a Previous HIT(~ 5 minutes)', 'Based on a previous HIT, you have qualified for this followup HIT.'),
('Type the text carefully and get rewarded', 'Type the text carefully and get highly rewarded on each task completion'),
('Copy and Paste Article Title and Article Body from URL Link', 'For this HIT, you will be given a web link. If the link contains an article, you will need to copy and past the article ‘Title’ and ‘Body’ into a form.'),
('Davis Cup rebranding', 'Understand tennis fans’ perceptions toward the rebrand of Davis Cup Finals'),
('Evaluate product review data field extractions!', 'Evaluate product review data field extractions! In each HIT, evaluate 4 extractions from a product webpage. This pays $0.15 per HIT, with a bonus of $0.05 when you maintain accuracy, write meaningful reasons and spend 30 seconds or more on each HIT. You need to qualify for this task; search for “[Qualification] Evaluate produce review data field extractions”. You cannot request the qualification, but you will get it when you complete both qualification HITs.'),
('Pick a Youtube thumbnail/title (~10 seconds)', '10 second task.'),
('Create 50 characters title for article about Viagra', 'Please write a title for an article about Viagra. It should be over 50 characters.'),
('Answer a survey about finding AI robot’s mistakes', '15 minutes (up to 50 minutes with $12 more bonus). Based on the AI robot’s explanations, figure out whether it makes a mistake.'),
('Detect border of the pupil and iris within an image (~ 1 minute)', 'Draw the outer border between pupil and iris in a precise and smooth way. We require at least 50 vertices!'),
('Fitness program membership purchase behavior during the COVID-19 pandemic', 'You are invited to participate in this study if you have participated in fitness program in forms of either onsite, or online, or both, during the COVID-19 pandemic.'),
('Answer a survey about voice assistant failures', 'Voice assistants such as Siri, Alexa, and Google Assistant can fail in many different ways. Evaluate how these example failures impact your perceptions of voice assistants’ abilities.'),
('Part 2 of The Role of Personality in Decision-Making Processes Related to Beverage Consumption(~ 35 minutes)', 'The main purpose of the study is to establish a pattern of general and specific factors influencing decision making processes in people with habitual consumption of particular beverages. The study will collect information related to goal-oriented decision making, personality characteristics, habitual consumption of beverages, and behavioural patterns.'),
('Summary Evaluation: Consistency and Informativeness', 'Evaluate whether summaries are consistent and informative to the article'),
('Quick Google Search for SEO Test', 'Use our keyword to find our website, and give us some basic info from the page it takes you to.'),
('(Time 2) Three part psychology study ~ 10-12 min each(~ 11 minutes)', 'Answer questions about emotions in the workplace'),
('Event relations (~ 15 mins)', 'Recognize the relation between two event is “match” or “conflict”.'),
('Answer questions about emotional expressions of faces and bodies', 'In this task, you will rate faces and bodies on whether you find their expressions angry or fearful.'),
('Qualification: Pair an actionable with its pre- and post-conditions', 'Please pair the actionables with their pre- and post-conditions'),
('Rules and regulations in parks and protected areas', 'Please read one message about parks and protected areas’ rules'),
('Turkish Names Survey', 'This survey asks respondents questions on their perceptions of some Turkish names. It is for TURKISH SPEAKERS ONLY. It takes 5 minutes to complete.'),
('Summarize images', 'Please briefly summarize image so that it can be picked out of a lineup'),
('Write a social media comment (~1 min) #7560', 'Given a post on a social media, write a nice positive comment for someone you follow.'),
('Verification [Vietnamese]: Is this claim verified by the given information? (~10-25min)', 'Requires proficiency in Vietnamese. Each HIT has 20 claims (~20-60s per claim). Find evidence for or against each claim. Label the claims as Verified, Rejected or Not-enough-information.'),
('Upload 1-minute screencast of a website', 'Record your computer’s screen and your voice while you spend 1 minute talking about your first visit to a website. Then upload the recording.'),
('Collecting direct email addresses from provided contact information', 'Review the provided contact information and try to find a valid direct email address using social media, search engine tools and other web resources.'),
('What type of a website is this?', 'What type of a website is this?'),
('Academic Research Survey on Artificial Intelligence and Explanation', 'This survey is part of an Explainable Artificial Intelligence Research Project. You will be asked to read one example explanation and answer questions about it and its quality. You will also be asked some questions about yourself.'),
('Y/N? This sentence says “Yay” at the end of the sentence.? (WARNING: may contain adult content.)', 'Select true or false for whether the sentence/paragraph says “Yay” at the end of the sentence.. (WARNING: may contain adult content. Discretion advised.)'),
('Categorize User Reviews', 'Read a short review of a how-to article and categorize it as positive or negative.'),
('Answer the questions associated with various aspects of ads (tone transition and social message)', 'Questions are asked about the tone transition, social message in advertisement videos . Please select the most relevant answer from the choices given and provide meaningful explanations.'),
('(only desktop users) Answer a survey about electronic bundle choices (The survey is not shown on smartphone screens.)', '(only desktop users) Give us your opinion about smart product choices. The survey is not shown on smartphone screens.'),
('Check quantity discount', 'What is the cart value when adding 2 the same items. ATTENTION quantity discount will apply only after adding to the cart'),
('Media use and perceptions related to the COVID-19 pandemic', 'Respond to an anonymous online survey which will ask about their preference for – and uses of – news media, as well as attitudes on race and gender. The survey concludes with demographic questions.'),
('Race in America: 2 part study(~ 20 minutes)', 'This is a 2-part study. This is part 2 of a two-part study that is invite-only. Upon successful completion of part 2 you will be paid $2.50. Please note, there are only a limited number of spots available in part 2.'),
('Crowdfunding Project Evaluations(~ 10 minutes)', 'This study asks you to evaluate a crowdfunding project based on its pitch video.'),
('Choose categories and sort tags for clips', 'Watch the video clip and choose the correct categories that match the video and sort the tags. Only prequalified workers can complete these clips. Also, for quality, around 1 in 5 clips will be sent for manual review the rest will be auto-approved so you can get paid quick. So pay attention and do your best! If you need help understanding any of the tasks, watch the tutorial video here: https://vimeo.com/359652854/3dc7075833'),
('STEM Learning 3.2(~ 10 minutes)', 'The focus of the research is to better understand how students learn STEM topics from video lectures. This is the second session of STEM Learning. You may not complete this study unless you have completed STEM Learning 3. Participation should take ~ 10 minutes'),
('Perceptions of Social Scenarios', 'We are looking for volunteers to participate in a research study examining perceptions of gender.'),
('Insects: A new feeding scope', 'This survey is a part of an effort to understand your consumption habits. This is a research about consumer behavior. The participation in this survey is voluntary, which means that you are free to participate or not, as well as give up at any time.'),
('Select the dialog you’d prefer to have', 'Select the dialog you enjoy the most'),
('Need you opinion about new toys', 'Give us your opinion about our products'),
('Share you Alexa conversation history for a research project', 'We would like to know how you interact with your voice assistants'),
('Parents of elementary school-aged children ($4.00 for eligible participants only)(~ 60 minutes)', 'Must be completed on laptop or desktop. Watch eight 1-minute video clips, complete computerized tasks, and answer questionnaires (~60 min)'),
('Ageing and thinking', 'A collection of 4 short scales to examine the effects of age on thinking'),
('Find the Instagram Username for a Given Celebrity', 'Use Google, social media platforms, or any other resources to find the Instagram username/handle for a given celebrity.'),
('Record audio of saying a specified term.', 'The recordings will be used for training machine learning models to recognize specific terms.'),
('Perceived Masculinity Based on Mental Health Treatment', 'If you decide to participate in this online study, you will be asked to answer questions addressing views and attitudes towards men pursuing various mental health treatments. Minimal risks are anticipated for participating in this study.'),
('Check if company rents properties.', 'LinkedIn Profiles Inspection'),
('Write an assistant conversation.', 'Write the transcript of a conversation between a user and an assistant to accomplish a common task across various scenarios.'),
('Eyewitness lineups', 'Be part of a psychological study on eyewitnesses and police line-ups. You will be asked to pick out a culprit (a face or object) from a line-up or make judgments about line-ups.'),
('[TRAINING] Identify the relationship between two sentences', 'You will be given two sentences and asked to determine their relationship: if one implies the other, if they contradict each other, or neither. You can also revise the sentences.'),
('Electric Cars (about 10 minutes)', 'Watch a few advertisements and then tell us what you think (10 questions)'),
('Language variety detection', 'Language dialect/variety identification'),
('Local-Level Model Explanation for Machine Learning Models', 'The goals is to provide narratives on how the different attributes or features used for the model training influence the prediction for a give test instance/case.'),
('Facebook ad classification with Detailed questions', 'You will be asked to answersome questions about an original snapshot of a Facebook ad on the external website.'),
('Record a one minute video of yourself', 'Record a one minute video of yourself performing some simple gestures.'),
('Answer Questions Comparing Two Objects', 'Answer 13 questions based on 2 videos.');
